# TCL File Generated by Component Editor 15.1
# Thu Jun 23 14:12:28 CEST 2016
# DO NOT MODIFY


# 
# laser "laser" v1.0
#  2016.06.23.14:12:28
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module laser
# 
set_module_property DESCRIPTION ""
set_module_property NAME laser
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ETTI4
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME laser
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL nios_interface_laser
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file nios_interface_laser.vhd VHDL PATH nios_interface_laser.vhd TOP_LEVEL_FILE
add_fileset_file baud_gen.vhd VHDL PATH baud_gen.vhd
add_fileset_file laser_memory.vhd VHDL PATH laser_memory.vhd
add_fileset_file modul_laser.vhd VHDL PATH modul_laser.vhd
add_fileset_file modul_uart.vhd VHDL PATH modul_uart.vhd
add_fileset_file send_cmd.vhd VHDL PATH send_cmd.vhd
add_fileset_file speicher.vhd VHDL PATH speicher.vhd
add_fileset_file uart_receive.vhd VHDL PATH uart_receive.vhd
add_fileset_file uart_send.vhd VHDL PATH uart_send.vhd


# 
# parameters
# 
add_parameter BAUD_GEN_PRESCALER_g INTEGER 2604
set_parameter_property BAUD_GEN_PRESCALER_g DEFAULT_VALUE 2604
set_parameter_property BAUD_GEN_PRESCALER_g DISPLAY_NAME BAUD_GEN_PRESCALER_g
set_parameter_property BAUD_GEN_PRESCALER_g TYPE INTEGER
set_parameter_property BAUD_GEN_PRESCALER_g UNITS None
set_parameter_property BAUD_GEN_PRESCALER_g ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BAUD_GEN_PRESCALER_g HDL_PARAMETER true
add_parameter RAM_DEPTH_g INTEGER 2048
set_parameter_property RAM_DEPTH_g DEFAULT_VALUE 2048
set_parameter_property RAM_DEPTH_g DISPLAY_NAME RAM_DEPTH_g
set_parameter_property RAM_DEPTH_g TYPE INTEGER
set_parameter_property RAM_DEPTH_g UNITS None
set_parameter_property RAM_DEPTH_g ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RAM_DEPTH_g HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 ce_n chipselect_n Input 1
add_interface_port avalon_slave_0 read_n read_n Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 reg_addr address Input 3
add_interface_port avalon_slave_0 write_data writedata Input 32
add_interface_port avalon_slave_0 read_data readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset RESET_n reset_n Input 1


# 
# connection point external_connection
# 
add_interface external_connection conduit end
set_interface_property external_connection associatedClock clock
set_interface_property external_connection associatedReset reset
set_interface_property external_connection ENABLED true
set_interface_property external_connection EXPORT_OF ""
set_interface_property external_connection PORT_NAME_MAP ""
set_interface_property external_connection CMSIS_SVD_VARIABLES ""
set_interface_property external_connection SVD_ADDRESS_GROUP ""

add_interface_port external_connection on_n on_n Output 1
add_interface_port external_connection tx txd Output 1
add_interface_port external_connection rx rxd Input 1

