# TCL File Generated by Component Editor 15.1
# Wed Jul 13 08:45:33 CEST 2016
# DO NOT MODIFY


# 
# Motor_Modul "Motor_Modul" v1.0
#  2016.07.13.08:45:33
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module Motor_Modul
# 
set_module_property DESCRIPTION ""
set_module_property NAME Motor_Modul
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ETTI4
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Motor_Modul
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL interface_motor_modul_mm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file baud_gen_mm.vhd VHDL PATH baud_gen_mm.vhd
add_fileset_file encoder_motor_mm.vhd VHDL PATH encoder_motor_mm.vhd
add_fileset_file interface_motor_modul_mm.vhd VHDL PATH interface_motor_modul_mm.vhd TOP_LEVEL_FILE
add_fileset_file motor_modul_mm.vhd VHDL PATH motor_modul_mm.vhd
add_fileset_file pid_regler_mm.vhd VHDL PATH pid_regler_mm.vhd
add_fileset_file uart_send_mm.vhd VHDL PATH uart_send_mm.vhd
add_fileset_file winkel_modul_mm.vhd VHDL PATH winkel_modul_mm.vhd


# 
# parameters
# 
add_parameter REG1_cntBits INTEGER 8
set_parameter_property REG1_cntBits DEFAULT_VALUE 8
set_parameter_property REG1_cntBits DISPLAY_NAME REG1_cntBits
set_parameter_property REG1_cntBits TYPE INTEGER
set_parameter_property REG1_cntBits UNITS None
set_parameter_property REG1_cntBits ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REG1_cntBits HDL_PARAMETER true
add_parameter REG2_cntBits INTEGER 16
set_parameter_property REG2_cntBits DEFAULT_VALUE 16
set_parameter_property REG2_cntBits DISPLAY_NAME REG2_cntBits
set_parameter_property REG2_cntBits TYPE INTEGER
set_parameter_property REG2_cntBits UNITS None
set_parameter_property REG2_cntBits ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REG2_cntBits HDL_PARAMETER true
add_parameter REG3_cntBits INTEGER 3
set_parameter_property REG3_cntBits DEFAULT_VALUE 3
set_parameter_property REG3_cntBits DISPLAY_NAME REG3_cntBits
set_parameter_property REG3_cntBits TYPE INTEGER
set_parameter_property REG3_cntBits UNITS None
set_parameter_property REG3_cntBits ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REG3_cntBits HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 ce_n chipselect_n Input 1
add_interface_port avalon_slave_0 read_n read_n Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 addr address Input 4
add_interface_port avalon_slave_0 write_data writedata Input 32
add_interface_port avalon_slave_0 read_data readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point encoder
# 
add_interface encoder conduit end
set_interface_property encoder associatedClock clock
set_interface_property encoder associatedReset ""
set_interface_property encoder ENABLED true
set_interface_property encoder EXPORT_OF ""
set_interface_property encoder PORT_NAME_MAP ""
set_interface_property encoder CMSIS_SVD_VARIABLES ""
set_interface_property encoder SVD_ADDRESS_GROUP ""

add_interface_port encoder encoder1_register_in encoder1_register_in Input 2
add_interface_port encoder encoder2_register_in encoder2_register_in Input 2


# 
# connection point uart_to_sabertooth
# 
add_interface uart_to_sabertooth conduit end
set_interface_property uart_to_sabertooth associatedClock clock
set_interface_property uart_to_sabertooth associatedReset ""
set_interface_property uart_to_sabertooth ENABLED true
set_interface_property uart_to_sabertooth EXPORT_OF ""
set_interface_property uart_to_sabertooth PORT_NAME_MAP ""
set_interface_property uart_to_sabertooth CMSIS_SVD_VARIABLES ""
set_interface_property uart_to_sabertooth SVD_ADDRESS_GROUP ""

add_interface_port uart_to_sabertooth uart_out uart_out Output 1


# 
# connection point led_drivestatus
# 
add_interface led_drivestatus conduit end
set_interface_property led_drivestatus associatedClock clock
set_interface_property led_drivestatus associatedReset ""
set_interface_property led_drivestatus ENABLED true
set_interface_property led_drivestatus EXPORT_OF ""
set_interface_property led_drivestatus PORT_NAME_MAP ""
set_interface_property led_drivestatus CMSIS_SVD_VARIABLES ""
set_interface_property led_drivestatus SVD_ADDRESS_GROUP ""

add_interface_port led_drivestatus LED_DriveStatus led_drivestatus_out Output 2

